import { z } from "zod"

export const categorySchema = z.object({
  id: z.number().optional().nullable(), // Auto-generated by Django
  category: z.string().max(100), // CharField with max_length of 100
  description: z.string().optional().nullable(), // TextField for description
});

export const categoryArraySchema = z.array(categorySchema)

export const subcategorySchema = z.object({
  id: z.number().optional(), // Auto-generated by Django
  category: categorySchema, // ForeignKey to Category model, represented as category ID
  subcategory: z.string().max(100), // CharField for subcategory name
});

export const subcategoryArraySchema = z.array(subcategorySchema)